[[milestones]]
name = "Start"

[[milestones]]
name = "Eye of Cthulhu"

[[milestones]]
name = "Evil Boss"

[[milestones]]
name = "Skeletron"

[[milestones]]
name = "Hardmode"

[[milestones]]
name = "Mechanical Bosses"

[[milestones]]
name = "Plantera"

[[milestones]]
name = "Golem"

[[milestones]]
name = "Lunatic Cultist"

[[milestones]]
name = "Moon Lord"
